# Generated by Django 4.1.4 on 2023-01-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Requisition',
            fields=[
                ('purchase_requisition_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=6)),
                ('submitted_date', models.DateField(blank=True, default=None, null=True)),
                ('purchase_requisition_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='quotation_total',
            new_name='quotation_total_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_date',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_created_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='salesman_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('purchase_order_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('finance_officer_id', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('total_price', models.FloatField()),
                ('purchase_order_created_date', models.DateField(blank=True, default=None, null=True)),
                ('delivery_date', models.DateField(blank=True, default=None, null=True)),
                ('purchase_order_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('quotation_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='purchase_requisition_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchase_requisition'),
        ),
    ]
