# Generated by Django 4.1.4 on 2023-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchase_requisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
