# Generated by Django 4.1.4 on 2023-01-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_Q', models.IntegerField()),
                ('item_total_price', models.FloatField()),
                ('item_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('quotation_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Requisition_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_PR', models.IntegerField()),
                ('item_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('purchase_requisition_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchase_requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_PO', models.IntegerField()),
                ('item_total_price', models.FloatField()),
                ('item_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('purchase_order_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchase_order')),
            ],
        ),
    ]
