# Generated by Django 4.1.4 on 2023-01-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quotation_item_purchase_requisition_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('product_total_sales', models.FloatField()),
                ('product_total_quantity', models.IntegerField()),
                ('salesman_total_sales', models.FloatField()),
                ('purchase_order_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchase_order')),
            ],
        ),
    ]
