# Generated by Django 4.1.5 on 2023-01-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchase_order_item_item_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cust_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Officer',
            fields=[
                ('fo_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fo_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('man_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('man_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('salesman_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_item',
            name='item_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_report',
            name='product_total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_item',
            name='item_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation_item',
            name='item_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
