# Generated by Django 4.1.5 on 2023-01-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_finance_officer_manager_salesman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='quotation_id',
            new_name='quotation',
        ),
        migrations.RenameField(
            model_name='purchase_order_item',
            old_name='purchase_order_id',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchase_order_report',
            old_name='purchase_order_id',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='purchase_requisition_id',
            new_name='purchase_requisition',
        ),
        migrations.RenameField(
            model_name='quotation_item',
            old_name='quotation_id',
            new_name='quotation',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='finance_officer_id',
        ),
        migrations.RemoveField(
            model_name='purchase_requisition',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='salesman_id',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='finance_officer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.finance_officer'),
        ),
        migrations.AddField(
            model_name='purchase_requisition',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='salesman',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salesman'),
        ),
    ]
