# Generated by Django 4.1.5 on 2023-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_manager_alter_purchase_order_finance_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_requisition',
            name='purchase_requisition_status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
