# Generated by Django 4.1.5 on 2023-01-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_salesman_manager_finance_officer_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_officer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='finance_officer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_fo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase_requisition',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='salesman',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_salesman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Finance_Officer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Salesman',
        ),
    ]
