# Generated by Django 4.1.5 on 2023-01-23 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_customer_alter_purchase_requisition_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('man_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Officer',
            fields=[
                ('fo_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
