# Generated by Django 4.1.5 on 2023-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_salesman_manager_finance_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_officer',
            name='fo_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
