# Generated by Django 4.1.4 on 2023-01-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_finance_officer_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase_Order_Report',
        ),
    ]
