# Generated by Django 4.1.4 on 2023-01-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_purchase_order_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_item',
            name='item_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
